rottenpotatoes/config/routes.rb
Rottenpotatoes::Application.routes.draw do
  resources :movies
  # map '/' to be a redirect to '/movies'
  root :to => redirect('/movies')

  get "find_similar/:id", to: 'movies#find_similar', as: 'find_similar'
end

rottenpotatoes/app/models/movie.rb
class Movie < ActiveRecord::Base
  def self.find_similar_movies(director_name)
    self.where(director: director_name).all
  end
# def similar_movies(movie)
#     puts "SIMILAR MOVIES"
#     puts movie
# end
end

rottenpotatoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rottenpotatoes/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    puts 'session'
    puts session[:id]
    puts 'params'
    puts params[:id]
    if session[:id]
      flash[:notice] = "'#{Movie.find(session[:id]).title}' has no director info"
      session[:id] = nil
    end
    @movies = Movie.all
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  #new
  def find_similar
    puts "FIND SIMILAR!!!"
    @movie = Movie.find params[:id]
    puts "DIR: #{@movie.director}"
    if @movie.director == ''
      session[:id] = params[:id]
      redirect_to movies_path
    else
      @movies = Movie.find_similar_movies(@movie.director)
    end
  end

  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :director, :release_date)
  end
end

rottenpotatoes/app/helpers/application_helper.rb
module ApplicationHelper
end

rottenpotatoes/app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  # def oddness(count)
  #   count.odd? ?  "odd" :  "even"
  # end
end

rottenpotatoes/app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

rottenpotatoes/app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>Rotten Potatoes!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg bg-primary text-white mb-3">
      <h1 class="title">Rotten Potatoes!</h1>
    </nav>
    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

rottenpotatoes/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %link(rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous")
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application', 'media' => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    %body
      %div.container
        %div.navbar.navbar-expand-lg.bg-primary.text-white
          %h1.title Rotten Potatoes!
        #main
          - if flash[:notice]
            %div.alert.alert-danger
              #notice.message= flash[:notice]
          - elsif flash[:warning]
            %div.alert.alert-danger
              #warning.message= flash[:warning]

          = yield

rottenpotatoes/app/views/movies/edit.html.erb
<h2>Edit Existing Movie</h2>
<%= form_tag movie_path(@movie), :method => :put do %>
    <%= label :movie, :title, 'Title', :class => 'col-form-label' %>
    <%= text_field :movie, 'title', :class => 'form-control' %>
    <%= label :movie, :director, 'Director', :class => 'col-form-label' %>
    <%= text_field :movie, 'director', :class => 'form-control' %>
    <%= label :movie, :rating, 'Rating', :class => 'col-form-label'  %>
    <%= select :movie, :rating, ['G','PG','PG-13','R','NC-17'], {}, {:class => 'form-control col-1'} %>
    <%= label :movie, :release_date, 'Released On', :class => 'col-form-label'  %>
    <%= date_select :movie, :release_date, {}, :class => 'form-control col-2 d-inline' %>
    <br/>
    <%= submit_tag 'Update Movie Info', :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', movies_path, :class => 'btn btn-secondary' %>
<% end %>

rottenpotatoes/app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h2 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info', :class => 'btn btn-primary'

rottenpotatoes/app/views/movies/find_similar.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<h2>Movies with Similar Director</h2>

<%#  Part 2: Start here... %>

<table class="table table-striped col-md-12" id="movies">
    <thead>
        <tr>
            <th>Movie Title</th>
            <th>Rating</th>
            <th>Director</th>
            <th>Release Date</th>
            <th>More Info</th>
        </tr>
    </thead>
    <tbody>
        <% @movies.each do |movie| %>
            <tr>
                <td>
                    <%= movie.title %>
                </td>
                <td>
                    <%= movie.rating %>
                </td>
                <td>
                    <%= movie.director %>
                </td>
                <td>
                    <%= movie.release_date %>
                </td>
                <td>
                    <%= link_to "More about #{movie.title}", movie_path(movie) %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= link_to 'Back to movie list', movies_path, :class => 'btn btn-primary col-2' %>

rottenpotatoes/app/views/movies/index.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<h2>All Movies</h2>

<%#  Part 2: Start here... %>

<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th>Movie Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= movie.title %>
        </td>
        <td>
          <%= movie.rating %>
        </td>
        <td>
          <%= movie.release_date %>
        </td>
        <td>
          <%= link_to "More about #{movie.title}", movie_path(movie) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add new movie', new_movie_path, :class => 'btn btn-primary' %>

rottenpotatoes/app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h2 All Movies

= form_tag movies_path, :method => :get, :id => 'ratings_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":release_date_sort", true if @date_header
  Include:
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @selected_ratings.include?(rating), :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => 'ratings_submit', :class => 'btn btn-primary'

%table#movies.table.table-striped.col-md-12
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Movie Title', movies_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      %th Rating
      %th{:class => @date_header}= link_to 'Release Date', movies_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

rottenpotatoes/app/views/movies/new.html.erb
<h2>Create New Movie</h2>

<%= form_tag movies_path, :class => 'form' do %>
  <%= label :movie, :title, 'Title', :class => 'col-form-label' %>
  <%= text_field :movie, :title, :class => 'form-control' %>
  <%= label :movie, :rating, 'Rating', :class => 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R','NC-17'], {}, {:class => 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', :class => 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, :class => 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, :class => 'btn btn-secondary' %>
<% end %>

rottenpotatoes/app/views/movies/new.html.haml
%h2 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes', :class => 'btn btn-primary'

rottenpotatoes/app/views/movies/show.html.erb
<!--  app/views/movies/show.html.erb -->
<h2>Details about
    <em><%= @movie.title %></em>
</h2>

<ul id="details">
    <li>
        Director:
        <%= @movie.director %>
    </li>
    <li>
        Rating:
        <%= @movie.rating %>
    </li>
    <li>
        Released on:
        <%= @movie.release_date.strftime("%B %d, %Y") %>
    </li>
</ul>

<h3>Description:</h3>
<p id="description">
    <%= @movie.description %>
</p>

<div class="row">
    <%= link_to 'Find Movies With Same Director', find_similar_path(@movie), :class => 'btn btn-primary col-2' %>
    <%= link_to 'Edit', edit_movie_path(@movie), :class => 'btn btn-primary col-2' %>
    <%= link_to 'Delete', movie_path(@movie), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
    <%= link_to 'Back to movie list', movies_path, :class => 'btn btn-primary col-2' %>
</div>

rottenpotatoes/app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h3 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h4 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-primary'
= link_to 'Back to movie list', movies_path

rottenpotatoes/app/views/movies/show_by_director.html.erb
<!--  This file is app/views/movies/show_by_director.html.erb -->
<h2>Other Movies by <%= @director %></h2>

<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th>Movie Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= movie.title %>
        </td>
        <td>
          <%= movie.rating %>
        </td>
        <td>
          <%= movie.release_date %>
        </td>
        <td>
          <%= link_to "More about #{movie.title}", movie_path(movie) %>
        </td>
      </tr>
    <% end %>
  </tbody>